AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create AWS CI/CD pipeline

Resources:
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: HelloWorldAppRepo
      RepositoryDescription: CodeCommit repository for Java Hello World app

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: HelloWorldAppBuild
      Source:
        Type: CODECOMMIT
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
      DeploymentGroupName: HelloWorldAppDeploymentGroup
      Ec2TagFilters:
        - Key: Name
          Value: CodeDeployEC2Instance
          Type: KEY_AND_VALUE
      DeploymentConfigName: CodeDeployDefault.OneAtATime

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

Outputs:
  CodeCommitRepoCloneUrlHttp:
    Description: Clone URL (HTTP) for CodeCommit Repository
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp
